---

driver:
     name: ec2
     aws_ssh_key_id: ghaleb2
     security_group_ids: ["sg-9006b8f8"]
     region: eu-central-1
     #availability_zone: b
     require_chef_omnibus: true
     #subnet_id: subnet-6e5d4c3b
     #iam_profile_name: chef-client
     instance_type: t2.medium
     associate_public_ip: true
     interface: public

transport:
     ssh_key: ~/.ssh/ghaleb2.pem


provisioner:
    name                  : ansible_push
    #verbose               : "vvvvvvvvvvv"
    ansible_config        : "test/ansible.cfg"
    idempotency_test      : False
    diff                  : False
    sudo                  : True

platforms:

#azure vm image list westeurope canonical ubuntuserver
  - name: ubuntu-14.04
    transport:
      username: ubuntu

  - name: ubuntu-16.04
    transport:
      username: ubuntu
#azure vm image list westeurope RedHat RHEL
  - name: rhel-7
    transport:
      username: ec2-user
#azure vm image list westeurope credativ Debian
  - name: debian-8
    transport:
      username: admin
#azure vm image list westeurope OpenLogic CentOS
  - name: centos-7
    transport:
      username: centos


suites:
  - name                  : default
    provisioner           :
        playbook          : "test/integration/manage/manage.yml"
